const Ride=require('../models/Ride');
const User=require('../models/User');
const {getIO}=require('../config/socket');
const COMMISSION_RATE=0.15;

const toggleOnlineStatus=async(req,res,next)=>{try{const {isOnline,currentLocation}=req.body;const update={isOnline:Boolean(isOnline)};if(currentLocation&&currentLocation.latitude!==undefined&&currentLocation.longitude!==undefined)update.location={type:'Point',coordinates:[Number(currentLocation.longitude),Number(currentLocation.latitude)],address:currentLocation.addressName||''};const user=await User.findByIdAndUpdate(req.user.id,{$set:update},{new:true}).select('-password');getIO().emit('driver_status_changed',{driverId:String(user._id),isOnline:user.isOnline});res.json({success:true,message:user.isOnline?'Driver is online.':'Driver is offline.',data:user});}catch(e){next(e);}};
const updateLocation=async(req,res,next)=>{try{const {latitude,longitude,address,heading=0}=req.body;if(latitude===undefined||longitude===undefined)return res.status(400).json({success:false,message:'Latitude and longitude are required.'});const user=await User.findByIdAndUpdate(req.user.id,{$set:{'location.type':'Point','location.coordinates':[Number(longitude),Number(latitude)],'location.address':address||'',heading:Number(heading),lastLocationUpdate:new Date()}},{new:true}).select('-password');getIO().emit('driver_location_changed',{driverId:String(user._id),latitude:Number(latitude),longitude:Number(longitude),heading:Number(heading)});res.json({success:true,message:'Location updated.',data:user.location});}catch(e){next(e);}};
const getNearbyRideRequests=async(req,res,next)=>{try{const rides=await Ride.find({status:'pending'}).populate('customer','fullName phone rating profilePictureUrl').sort({createdAt:-1}).limit(50);res.json({success:true,data:rides});}catch(e){next(e);}};
const acceptRide=async(req,res,next)=>{try{const ride=await Ride.findById(req.body.rideId);if(!ride)return res.status(404).json({success:false,message:'Ride not found.'});if(ride.status!=='pending')return res.status(400).json({success:false,message:'Ride is no longer available.'});ride.driver=req.user.id;ride.status='accepted';ride.acceptedAt=new Date();await ride.save();await ride.populate([{path:'customer',select:'fullName phone rating profilePictureUrl'},{path:'driver',select:'fullName phone rating vehicle profilePictureUrl'}]);getIO().to(`ride_${ride._id}`).emit('ride_status_updated',{rideId:String(ride._id),status:'accepted',driver:ride.driver});res.json({success:true,message:'Ride accepted.',data:ride});}catch(e){next(e);}};
const updateTripStatus=async(req,res,next)=>{try{const {rideId,status}=req.body;const map={ARRIVED_AT_PICKUP:'arrived',TRIP_STARTED:'in_progress',COMPLETED:'completed',arrived:'arrived',in_progress:'in_progress',completed:'completed'};const normalized=map[status];if(!rideId||!normalized)return res.status(400).json({success:false,message:'Valid rideId and status are required.'});const ride=await Ride.findById(rideId);if(!ride)return res.status(404).json({success:false,message:'Ride not found.'});if(String(ride.driver)!==String(req.user.id))return res.status(403).json({success:false,message:'Ride is not assigned to you.'});ride.status=normalized;if(normalized==='arrived')ride.arrivedAt=new Date();if(normalized==='in_progress')ride.startedAt=new Date();if(normalized==='completed'){ride.completedAt=new Date();const commission=Math.round(ride.fare*COMMISSION_RATE);ride.commissionAmount=commission;ride.driverEarnings=ride.fare-commission;await User.findByIdAndUpdate(req.user.id,{$inc:{totalRides:1,totalEarnings:ride.driverEarnings,unpaidCommission:commission}});}await ride.save();getIO().to(`ride_${rideId}`).emit('ride_status_updated',{rideId,status:normalized});res.json({success:true,message:'Trip status updated.',data:ride});}catch(e){next(e);}};
const getCompletedTrips=async(req,res,next)=>{try{const rides=await Ride.find({driver:req.user.id,status:'completed'}).populate('customer','fullName phone rating profilePictureUrl').sort({completedAt:-1});res.json({success:true,data:rides});}catch(e){next(e);}};
const getDriverEarnings=async(req,res,next)=>{try{const user=await User.findById(req.user.id).select('totalRides totalEarnings unpaidCommission commissionReceipts');const paid=user.commissionReceipts?.filter(r=>r.status==='approved').reduce((sum,r)=>sum+r.amountPaid,0)||0;res.json({success:true,data:{totalTripsCompleted:user.totalRides,totalEarnings:user.totalEarnings,pendingCommissionAmount:user.unpaidCommission,paidCommissionAmount:paid,currency:'NGN',commissionRatePercentage:COMMISSION_RATE*100}});}catch(e){next(e);}};
const getDriverReceipts=async(req,res,next)=>{try{const user=await User.findById(req.user.id).select('commissionReceipts');const data=(user.commissionReceipts||[]).map(r=>({id:String(r._id),amountPaid:r.amountPaid,paymentReference:r.paymentReference,receiptUrl:r.receiptUrl,status:r.status==='pending_verification'?'PENDING_VERIFICATION':r.status.toUpperCase(),createdAt:r.submittedAt}));res.json({success:true,data});}catch(e){next(e);}};
const uploadCommissionReceipt=async(req,res,next)=>{try{const {receiptUrl,amountPaid,paymentReference,notes}=req.body;if(!receiptUrl||!amountPaid)return res.status(400).json({success:false,message:'Receipt URL and amount paid are required.'});const user=await User.findByIdAndUpdate(req.user.id,{$push:{commissionReceipts:{receiptUrl,amountPaid:Number(amountPaid),paymentReference:paymentReference||'',notes:notes||'',status:'pending_verification',submittedAt:new Date()}}},{new:true}).select('commissionReceipts');res.status(201).json({success:true,message:'Commission receipt submitted.',data:user.commissionReceipts.at(-1)});}catch(e){next(e);}};
module.exports={toggleOnlineStatus,updateLocation,getNearbyRideRequests,acceptRide,updateTripStatus,getCompletedTrips,getDriverEarnings,getDriverReceipts,uploadCommissionReceipt};
