const express = require('express');
const router = express.Router();

const {
  register,
  login,
  getMe,
  updateProfile,
  updatePassword,
  forgotPassword,
  resetPassword,
} = require('../controllers/authController');

const {
  requestFounderPasswordSetup,
  setAdminPassword,
} = require('../controllers/adminController');

const { protect } = require('../middleware/authMiddleware');

// ============================================================
// PUBLIC AUTH ROUTES
// ============================================================

/**
 * Register a new customer or driver.
 */
router.post('/register', register);

/**
 * Login customer, driver, or authorized admin.
 */
router.post('/login', login);

/**
 * Request password setup for an authorized Founder Admin.
 *
 * This endpoint verifies that the email belongs to one of the
 * configured Founder Admin accounts and sends the password
 * setup email.
 */
router.post(
  '/admin/request-password-setup',
  requestFounderPasswordSetup
);

/**
 * Set the password for an authorized admin account.
 *
 * The request must contain the password-reset/setup token
 * generated by requestFounderPasswordSetup.
 */
router.post(
  '/admin/set-password',
  setAdminPassword
);

// ============================================================
// PROTECTED AUTH ROUTES
// ============================================================

/**
 * Get currently authenticated user's profile.
 */
router.get('/me', protect, getMe);

/**
 * Get currently authenticated user's profile.
 *
 * Kept as an alias for compatibility with the frontend.
 */
router.get('/profile', protect, getMe);

/**
 * Update currently authenticated user's profile.
 */
router.put('/profile', protect, updateProfile);

/**
 * Change password for the currently authenticated user.
 */
router.put(
  '/update-password',
  protect,
  updatePassword
);

/**
 * Request a normal password reset.
 */
router.post(
  '/forgot-password',
  forgotPassword
);

/**
 * Complete a normal password reset.
 */
router.post(
  '/reset-password',
  resetPassword
);

/**
 * Sign out.
 *
 * JWT authentication is stateless, so the client removes its
 * stored token after receiving this successful response.
 */
router.post(
  '/signout',
  protect,
  (req, res) => {
    return res.json({
      success: true,
      message: 'Signed out successfully.',
    });
  }
);

// ============================================================
// EXPORT ROUTER
// ============================================================

module.exports = router;
