const express=require('express');
const router=express.Router();
const {toggleOnlineStatus,updateLocation,getNearbyRideRequests,acceptRide,updateTripStatus,getCompletedTrips,getDriverEarnings,getDriverReceipts,uploadCommissionReceipt}=require('../controllers/driverController');
const {protect,authorize}=require('../middleware/authMiddleware');
const {uploadSingleFile}=require('../middleware/uploadMiddleware');
router.use(protect,authorize('driver'));
router.put('/toggle-status',toggleOnlineStatus);
router.post('/status',toggleOnlineStatus);
router.put('/location',updateLocation);
router.get('/requests',getNearbyRideRequests);
router.get('/ride-offers',getNearbyRideRequests);
router.post('/accept-ride',acceptRide);
router.patch('/update-trip-status',updateTripStatus);
router.get('/trips/completed',getCompletedTrips);
router.get('/account/summary',getDriverEarnings);
router.get('/earnings',getDriverEarnings);
router.get('/receipts',getDriverReceipts);
router.post('/receipt',uploadSingleFile('receipt'),(req,res,next)=>{if(req.file?.storedUrl)req.body.receiptUrl=req.file.storedUrl;next();},uploadCommissionReceipt);
router.post('/commission-receipt',uploadCommissionReceipt);
router.post('/commission/upload-receipt',uploadSingleFile('receipt'),(req,res,next)=>{if(req.file?.storedUrl)req.body.receiptUrl=req.file.storedUrl;next();},uploadCommissionReceipt);
router.get('/commission/receipts',getDriverReceipts);
module.exports=router;
