import apiClient from './client';
export type MobilityOptionType='STANDARD'|'PREMIUM'|'SHARED';
export type RideStatus='PENDING'|'ACCEPTED'|'ARRIVED'|'ARRIVING'|'IN_PROGRESS'|'COMPLETED'|'CANCELLED';
export interface LocationCoordinates{latitude:number;longitude:number;addressName?:string;}
export interface MobilityOptionDetail{id:MobilityOptionType;name:string;description:string;estimatedPrice:number;currency:string;estimatedDurationMinutes:number;capacity:number;}
export interface FareEstimateRequest{pickupLocation:LocationCoordinates;destinationLocation:LocationCoordinates;}
export interface FareEstimateResponse{distanceKm:number;estimatedDurationMinutes:number;options:MobilityOptionDetail[];fare?:number;distanceText?:string;durationText?:string;}
export interface RequestRidePayload{pickupLocation:LocationCoordinates;destinationLocation:LocationCoordinates;mobilityType:MobilityOptionType;agreedPrice:number;paymentMethod:'TRANSFER'|'CARD'|'CASH';}
export interface DriverDetails{id:string;fullName:string;phoneNumber:string;rating:number;vehicleModel:string;vehiclePlateNumber:string;vehicleColor:string;avatarUrl?:string;currentLocation?:LocationCoordinates;}
export interface RideBooking{id:string;_id?:string;riderId?:string;driver?:DriverDetails;status:RideStatus|Lowercase<RideStatus>;pickupLocation:LocationCoordinates;destinationLocation:LocationCoordinates;mobilityType?:MobilityOptionType;fareAmount?:number;fare?:number;currency?:string;paymentMethod:string;createdAt:string;}
export interface DriverLocationTracking{rideId:string;driverId:string;latitude:number;longitude:number;heading?:number;estimatedArrivalMinutes:number;}
const point=(x:LocationCoordinates)=>({type:'Point',coordinates:[x.longitude,x.latitude],address:x.addressName||''});
const mapRide=(r:any):RideBooking=>({...r,id:String(r._id||r.id),riderId:String(r.customer?._id||r.customer||''),fareAmount:r.fare,driver:r.driver?{id:String(r.driver._id),fullName:r.driver.fullName,phoneNumber:r.driver.phone, rating:r.driver.rating,vehicleModel:r.driver.vehicle?.model||'',vehiclePlateNumber:r.driver.vehicle?.licensePlate||'',vehicleColor:r.driver.vehicle?.color||'',avatarUrl:r.driver.profilePictureUrl,currentLocation:r.driver.location?.coordinates?{longitude:r.driver.location.coordinates[0],latitude:r.driver.location.coordinates[1]}:undefined}:undefined,pickupLocation:r.pickupLocation?.coordinates?{longitude:r.pickupLocation.coordinates[0],latitude:r.pickupLocation.coordinates[1],addressName:r.pickupLocation.address}:r.pickupLocation,destinationLocation:r.dropoffLocation?.coordinates?{longitude:r.dropoffLocation.coordinates[0],latitude:r.dropoffLocation.coordinates[1],addressName:r.dropoffLocation.address}:r.dropoffLocation});
export const riderApi={
 getFareEstimates:async(payload:FareEstimateRequest)=>{const r=await apiClient.post<{success:boolean;data:any}>('/rides/fare',{pickup:{latitude:payload.pickupLocation.latitude,longitude:payload.pickupLocation.longitude},dropoff:{latitude:payload.destinationLocation.latitude,longitude:payload.destinationLocation.longitude}});const d=r.data.data;return {distanceKm:d.distanceInKm,estimatedDurationMinutes:d.durationInMinutes,options:[{id:'STANDARD',name:'Standard',description:'Everyday ride',estimatedPrice:d.fare,currency:'NGN',estimatedDurationMinutes:d.durationInMinutes,capacity:4},{id:'PREMIUM',name:'Premium',description:'Comfort ride',estimatedPrice:Math.round(d.fare*1.3),currency:'NGN',estimatedDurationMinutes:d.durationInMinutes,capacity:4},{id:'SHARED',name:'Shared',description:'Lower-cost shared ride',estimatedPrice:Math.round(d.fare*0.8),currency:'NGN',estimatedDurationMinutes:d.durationInMinutes+5,capacity:4}],fare:d.fare,distanceText:d.distanceText,durationText:d.durationText};},
 requestRide:async(payload:RequestRidePayload)=>{const r=await apiClient.post<{success:boolean;data:any}>('/rides/request',{pickupLocation:point(payload.pickupLocation),dropoffLocation:point(payload.destinationLocation),fareAmount:payload.agreedPrice,paymentMethod:payload.paymentMethod});return mapRide(r.data.data);},
 getRideDetails:async(id:string)=>{const r=await apiClient.get<{success:boolean;data:any}>(`/rides/${id}`);return mapRide(r.data.data);},
 trackDriverLocation:async(id:string)=>{const r=await apiClient.get<{success:boolean;data:any}>(`/tracking/${id}/location`).catch(()=>null);if(r?.data?.data)return r.data.data;const ride=await riderApi.getRideDetails(id);const loc=ride.driver?.currentLocation;return {rideId:id,driverId:ride.driver?.id||'',latitude:loc?.latitude||0,longitude:loc?.longitude||0,heading:0,estimatedArrivalMinutes:0};},
 cancelRide:async({rideId,cancellationReason}:{rideId:string;cancellationReason:string})=>{const r=await apiClient.post('/rides/cancel-ride',{rideId,reason:cancellationReason});return r.data;},
 rateDriver:async()=>({success:false,message:'Rating endpoint is not implemented yet.'}),
 getTripHistory:async()=>{const r=await apiClient.get<{success:boolean;data:any[]}>('/rides/history');const rides=r.data.data.map(mapRide);return {completedTrips:rides.filter(x=>String(x.status).toLowerCase()==='completed'),cancelledTrips:rides.filter(x=>String(x.status).toLowerCase()==='cancelled')};},
 sendTrackingEmail:async(rideId:string,email:string)=>{const r=await apiClient.post(`/tracking/${rideId}/send-tracking-email`,{email});return r.data;},
};
export default riderApi;
